//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN01-COREUNITS
        ///Core Units in Undergraduate Engineering
        ///Yellow
        ///EGB100,0,1,Core
        ///EGB113,1,1,Core
        ///EGB120,2,1,Option
        ///MXB161,3,1,MathOption
        ///MZB125,4,1,MathOption
        ///EGB111,0,2,Core
        ///EGB121,1,3,Core
        ///EGB123,2,2,Option
        ///MZB126,3.5,2,Core
        ///BVB101,6.0,1,Option
        ///CRB040,5.0,1,Option
        ///CVB101,7.0,1,Option
        ///ERB101,6.0,2,Option
        ///ERB102,8.0,1,Option
        ///ERB204,6,3,Option
        ///EVB102,7,2,Option
        ///EVB203,7,3,Option
        ///IFB104,9.0,1,Option
        ///KKB191,10.0,1,Option
        ///KKB193,8.0,2,Option
        ///MXB105,5.0,2,Option
        ///MXB106,9.0,2,Option
        ///MXB107,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EN01 {
            get {
                return ResourceManager.GetString("EN01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN01-COREUNITS
        ///Core Units in Undergraduate Information Technology
        ///Yellow
        ///IFB102,0.0,1,Core
        ///IFB103,7.0,1,Core
        ///IFB104,2.0,1,Core
        ///IFB105,5.0,1,Core
        ///BSB305,2.0,4.5,Option
        ///CAB201,1.0,3.0,Option
        ///CAB202,0.0,3.0,Option
        ///CAB210,9.0,3.0,Option
        ///CAB230,2.0,3.0,Option
        ///CAB240,5.0,4.5,Option
        ///IAB201,5.0,3.0,Option
        ///IAB202,8.0,3.0,Option
        ///IAB206,4.0,3.0,Option
        ///IAB207,6.0,3.0,Option
        ///IAB230,3.0,3.0,Option
        ///IAB250,7.0,3.0,Option
        ///IGB180,3.0,4.5,Option
        ///MZB151,4.0,4.5,Option
        ///
        ///IN01MJR-COMPSC
        ///Computer Science Maj [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IN01 {
            get {
                return ResourceManager.GetString("IN01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSB305,1,12,NEXT Innovation Challenge,
        ///BVB101,2,12,Foundations of Biology,
        ///CAB201,3,12,Programming Principles,EGD126 or ENB246 or IFB104 or INB104 or ITD104 or MAB220 or MXB103 or MZB126
        ///CAB202,3,12,Microprocessors and Digital Systems,((IFB102 or INB102 or ITD102) and (IFB104 or ITD104)) or (EGD126 or ENB240 or MZB126)
        ///CAB203,1,12,Discrete Structures,EGD126 or IFB104 or ITD104 or MZB126
        ///CAB210,2,12,People Context and Technology,EGB100 or ENB100 or IFB103 or INB103 or INB182 or ITD103
        ///CAB220,2,12,Fundamental [rest of string was truncated]&quot;;.
        /// </summary>
        public static string units {
            get {
                return ResourceManager.GetString("units", resourceCulture);
            }
        }
    }
}
